ArtSocial/ArtSocial/Models/DetailProduct.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace ArtSocial.Models
{
    [Table("View_DetailProduct")]
    public class DetailProduct
    {
        [Key]
        public int ArtID { get; set; }
        public string? ArtName { get; set; }
        public int? CategoryID { get; set; }
        public string? Abstract { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UserID { get; set; }
        public string? Image { get; set; }
        public string? Description { get; set; }
        public int? Prices { get; set; }
        public string? FullName { get; set; }
        public string? AvatarPath { get; set; }
        public bool? isAdmin { get; set; }
        public string? CategoryName { get; set; }

        public bool? Accept { get; set; }

    }
}

ArtSocial/ArtSocial/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.Identity.Client;

namespace ArtSocial.Models
{
    [Table("tblArtProduct")]
    public class Product
    {
        [Key]
        public int ArtID { get; set; }
        public string? ArtName { get; set; }
        public int? CategoryID { get; set; }
        public string? Abstract { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UserID { get; set; } 
        public string? Description { get; set; }
        public string? Image { get; set; }
        public int? Prices { get; set; }
        public bool? Accept { get; set; }

        public bool? Selled { get; set; }
    }
}

ArtSocial/ArtSocial/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using ArtSocial.Models;
namespace ArtSocial.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly DataContext dataContext;
        public ProductController(DataContext dataContext)
        {
            this.dataContext = dataContext;
        }
        public IActionResult Index()
        {
            var prod= dataContext.Products.ToList();
            return View(prod);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mn = dataContext.Products.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var mn = dataContext.Products.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            dataContext.Products.Remove(mn);
            dataContext.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult WaitingAccept()
        {
            var wac = dataContext.Products.Where(m => m.Accept == false).ToList();
            
            return View(wac);
        }


        public IActionResult Accept(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mn = dataContext.Products.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Accept(Product mn)
        {
            if (ModelState.IsValid)
            {
                dataContext.Products.Update(mn);
                dataContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }



    }
}

ArtSocial/ArtSocial/Controllers/MyCartController.cs
using Microsoft.AspNetCore.Mvc;
using ArtSocial.Utilities;
using ArtSocial.Models;
using System.Drawing.Text;
using Microsoft.EntityFrameworkCore;

namespace ArtSocial.Controllers
{
    public class MyCartController : Controller
    {
        private readonly DataContext _context;
        public MyCartController(DataContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var cart = (
                from m in _context.detailMyCarts
                where m.UserBuyID == Functions._UserID
                select m
                ).ToList();

            //var cart2 = _context.detailMyCarts.Where(m => m.UserBuyID == 2).ToList();
            return View(cart);
        }


        public IActionResult AddtoCart(int ArtID)
        {
            
                var toCart = new MyCart();
                toCart.ArtID = ArtID;
                toCart.UserBuyID = Functions._UserID;
                _context.Add(toCart);
                _context.SaveChanges();
                return View();
        }


        public IActionResult DeleteonCart(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mn = _context.MyCarts.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            return View(mn);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteonCart(int id)
        {
            var mn = _context.MyCarts.Find(id);
            if (mn == null)
            {
                return NotFound();
            }
            _context.MyCarts.Remove(mn);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

ArtSocial/ArtSocial/Controllers/ProductController.cs
using ArtSocial.Components;
using ArtSocial.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using ArtSocial.Utilities;
namespace ArtSocial.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DataContext _context;


        public ProductController(ILogger<HomeController> logger, DataContext context)
        {
            _logger = logger;
            _context = context;
        }
        [HttpGet("/list-tac-pham{id:int}")]
        public IActionResult Index(int? id)
        {
            if(id == null || id ==0)
            {
                var mn = (
                    from m in _context.DetailProducts
                    select m
                    ).OrderByDescending(m=> m.CreatedDate).ToList();
                return View(mn);
            }
            else
            {
                var vl = _context.DetailProducts.Where(m => m.CategoryID == id).ToList();
                //var ml = (
                //    from m in _context.DetailProducts
                //    where m.CategoryID == id
                //    select m
                //    ).ToList();
                return View(vl);
            }
        }

        [HttpGet("/tac-pham-{id:int}")]
        public IActionResult DetailProduct(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                var dp = _context.DetailProducts.FirstOrDefault(m => m.ArtID == id);
                return View(dp);
            }
            
        }


        public IActionResult Comment_Acction(string? commentstext, string ArtID)
        {
            if (ModelState.IsValid)
            {
                BaseComment comment = new BaseComment();
                comment.CreatedDate = DateTime.Now;
                comment.ArtID = int.Parse(ArtID);
                comment.CommentText = commentstext;
                comment.UserID = Functions._UserID;
                _context.baseComments.Add(comment);
                _context.SaveChanges();
                
            }
            string retu = "/tac-pham-" + ArtID;
            return Redirect(retu);
        }



        public IActionResult AddProduct()
        {
            var listCate = (
                from m in _context.Categories
                select new SelectListItem()
                {
                    Text = m.CategoryName,
                    Value = m.CategoryID.ToString()
                }
      ).ToList();
            ViewBag.listCate = listCate;
            return View();
        }
        [HttpPost]
        public IActionResult AddProduct(Product product)
        {
            if (ModelState.IsValid)
            {
                product.CreatedDate = DateTime.Now;
                product.UserID = Functions._UserID;
                product.Accept = false;
                _context.Products.Add(product);
                _context.SaveChanges();
                Functions._uploaddone = "Upload thành công";
            }
            return Redirect("AddProduct");
        }

        public IActionResult Search(string str)
        {
            var results = _context.DetailProducts
                             .Where(t => t.ArtName.Contains(str))
                             .ToList();
            return View(results);
        }
    }
}

ArtSocial/ArtSocial/Views/Product/AddProduct.cshtml
@using ArtSocial.Models;
@model ArtSocial.Models.Product;
@using ArtSocial.Utilities;
            <header class="site-header d-flex flex-column justify-content-center align-items-center">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-12 col-12 text-center">

                            <h2 class="mb-0">Thêm tác phẩm</h2>
                        </div>

                    </div>
                </div>
            </header>
            <section class="contact-section section-padding pt-0">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-8 col-12 mx-auto">
                            <div class="section-title-wrap mb-5">
                                <h4 class="section-title">Làm phong phú cho khối tác phẩm của bạn</h4>
                            </div>
                <h4 style="color:red" class="section-title">@Functions._uploaddone</h4>
                            <form asp-action="AddProduct" asp-controller="Product" method="post" class="custom-form contact-form">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-12">
                                        <label asp-for="ArtName" for="floatingInput">Tên tác phẩm: </label>
                                        <div class="form-floating">
                                            <input type="text" asp-for="ArtName" name="ArtName" id="full-name" class="form-control" placeholder="Full Name" required="">
                                            
                                            
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-md-6 col-12">
                                    <label for="floatingInput" asp-for="CategoryID">Chọn thể loại</label>
                                        <div class="form-floating">
                                            <select name="CategoryID" id="" asp-for="CategoryID" class="form-control" asp-items="@(new SelectList(ViewBag.listCate,"Value","Text"))">
                                            </select>
                                        </div>
                                    </div>


                                    <div class="col-lg-12 col-12">
                                        <div class="col-lg-6 col-md-6 col-12">
                                <label asp-for="Prices" for="floatingInput">GIá tiền </label>
                                            <div class="form-floating">
                                                <input type="number" asp-for="Prices" name="Prices" id="full-name" class="form-control" placeholder="Full Name" required="">


                                            </div>
                                        </div>


                            <label asp-for="Image" for="floatingInput">Hình ảnh</label>
                                        <div class="form-floating">
                                            <input asp-for="Image" type="text" name="Image" id="name" class="form-control" placeholder="Name" required="">
                                            
                                            
                                        </div>
                            <label for="floatingTextarea" asp-for="Description">Mô tả</label>
                                        <div class="form-floating">
                                            <textarea asp-for="Description" class="form-control" id="message" name="Description" placeholder="Describe message here"></textarea>
                                            
                                            
                                        </div>
                                    </div>

                                    <div class="col-lg-4 col-12 ms-auto">
                                        <button type="submit" class="form-control">Submit</button>
                                    </div>
                       
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </section>

ArtSocial/ArtSocial/Views/Product/DetailProduct.cshtml
@using ArtSocial.Models;
@using Microsoft.AspNetCore.Html;
@using Microsoft.AspNetCore;

<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 text-center">

                <h2 class="mb-0">Tác phẩm</h2>
            </div>

        </div>
    </div>
</header>


<section class="latest-podcast-section section-padding pb-0" id="section_2">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-lg-10 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Thông tin tác phẩm</h4>
                </div>

                <div class="row">
                    <div class="col-lg-3 col-12">
                        <div class="custom-block-icon-wrap">
                            <div class="custom-block-image-wrap custom-block-image-detail-page">
                                <img src="@Model.Image" class="custom-block-image img-fluid" alt="">
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-9 col-12">
                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <a href="#">
                                        <i class="bi-play"></i>
                                        Play now
                                    </a>
                                </small>

                                <small>
                                    <i class="bi-clock-fill custom-icon"></i>
                                    50 Minutes
                                </small>

                                <small class="ms-auto">Episode <span class="badge">15</span></small>
                            </div>

                            <h2 class="mb-2">Tác phẩm: @Model?.ArtName</h2>
                            <p>T&aacute;c giả:&nbsp;<a href="https://www.dohoa360.com/tieu-chi-danh-gia-mot-thiet-ke-tot/#" title="Đồ họa 360">@Model.FullName</a></p>
                            <p>
                                @(new HtmlString(Model?.Description))
                            </p>
                            Giá tiền: @Model?.Prices
                            <h4>Bình luận</h4>
                            <div class="profile-block profile-detail-block d-flex flex-wrap align-items-center mt-5">
                                
                                
                               
                                        <img src="images/verified.png" class="verified-image img-fluid" alt="">
                                <div class="d-flex mb-3 mb-lg-0 mb-md-0">




                                @*    <form action="#" method="get" class="custom-form search-form flex-fill me-3" role="search">
                                        <div class="input-group input-group-lg">
                                            <input name="search" type="search" class="form-control" id="search" placeholder="Bình luận tại đây !" aria-label="Search">

                                            <button type="submit" class="form-control" id="submit">
                                                Gửi
                                            </button>
                                        </div>
                                    </form>*@



                                    <form action="@Url.Action("Comment_Acction", "Product")" method="get" class="custom-form search-form flex-fill me-3" role="search" >
                                        <div class="input-group input-group-lg">
                                            <input type="text" name="ArtID" value="@Model?.ArtID" hidden  />
                                            <input type="text" name="commentstext" placeholder="Bình luận" class="form-control">
                                            <button type="submit" class="form-control" id="submit"> > </button> 
                                        </div>
                                    </form>





                                </div>
                                <ul>
                                        @await Component.InvokeAsync("Comments", new {ArtID = Model?.ArtID})
                                        </ul>
                                
                               
                            </div>
                            


              


                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

@await Component.InvokeAsync("RecentArtView")

@*
@page
@model IndexModel
@addTagHelper *, WebApplication
<div class="p-3 m-3 bg-success">@await Component.InvokeAsync("ParamSample", new { greeting = "Xin chào", name = "Ngài tổng thống" })</div>
<div class="p-3 m-3 bg-secondary"><vc:param-sample greeting="Xin chào" name="Ngài tổng thống" /></div>
*@

ArtSocial/ArtSocial/Views/Product/Index.cshtml
@model IList<DetailProduct>
<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 text-center">

                <h2 class="mb-0">Danh sách tác phẩm</h2>
            </div>

        </div>
    </div>
</header>


<section class="latest-podcast-section section-padding pb-0" id="section_2">
    <div class="container">
        <div class="col-lg-12 col-12 mx-auto">
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-lg justify-content-center mt-5">
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    <li class="page-item "><a class="page-link" href="/list-tac-pham1">Trừu tượng</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham2">Logo</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham3">Banner</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham4">Poster</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham5">Nữ tính</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham6">3D</a></li>

                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="row justify-content-center">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Danh sác tác phẩm</h4>
                </div>
            </div>
    @if(Model.Count() == 0){
        <h5 style="color:blueviolet"> ----------------      Hiện chưa có tác phẩm nào       -------------------</h5>
    }
       
            @foreach (var item in Model)
            {
                string url = "/tac-pham-" + item.ArtID.ToString();
                <div class="col-lg-6 col-12 mb-4">
                    <div class="custom-block d-flex">
                        <div class="">
                            <div class="custom-block-icon-wrap">
                                <div class="section-overlay"></div>
                                <a href="detail-page.html" class="custom-block-image-wrap">
                                    <img src="@item.Image" alt="" height="112px" width="112px">
                                        @item.Prices

                                </a>
                            </div>

                            <div class="mt-2">
                                <form action="@Url.Action("AddtoCart", "MyCart")" method="get" class="custom-form search-form flex-fill me-3" role="search">
                                    <div class="input-group input-group-lg">
                                        <input type="text" name="ArtID" value="@item?.ArtID" hidden />
                                        <button type="submit" class="form-control" id="submit"> Add to cart </button>
                                    </div>
                                </form>
                                @*<a href="#" class="btn custom-btn">
                                    Add to cart
                                </a>*@
                            </div>
                        </div>

                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <i class="bi-clock-fill custom-icon"></i>
                                    50 Minutes
                                </small>

                                <small>Episode <span class="badge">15</span></small>
                            </div>

                            <h5 class="mb-2">
                                <a href="@url">
                                    @item.ArtName
                                </a>
                            </h5>

                            <div class="profile-block d-flex">
                                <img src="~/@item.AvatarPath" class="profile-block-image img-fluid" alt="">

                                <p>
                                    @item.FullName
                                    <img src="~/Web/images/verified.png" class="verified-image img-fluid" alt="">
                                    <strong>Thành viên</strong>
                                </p>
                            </div>

                            @*<p class="mb-0">@(new HtmlString(item.Description.Remove(48))) ...</p>*@
                            <p class="mb-0">@item.Abstract</p>
                            <div class="custom-block-bottom d-flex justify-content-between mt-3">
                                <a href="#" class="bi-headphones me-1">
                                    <span>120k</span>
                                </a>

                                <a href="#" class="bi-heart me-1">
                                    <span>42.5k</span>
                                </a>

                                <a href="#" class="bi-chat me-1">
                                    <span>11k</span>
                                </a>

                                <a href="#" class="bi-download">
                                    <span>50k</span>
                                </a>
                            </div>
                        </div>

                        <div class="d-flex flex-column ms-auto">
                            <a href="#" class="badge ms-auto">
                                <i class="bi-heart"></i>
                            </a>

                            <a href="#" class="badge ms-auto">
                                <i class="bi-bookmark"></i>
                            </a>
                        </div>
                    </div>
                </div>

            }

        </div>
        
    </div>
</section>
  @await Component.InvokeAsync("RecentArtView")


@*<form action="@Url.Action("AddtoCart", "MyCart")" method="get" class="custom-form search-form flex-fill me-3" role="search">
    <div class="input-group input-group-lg">
        <input type="text" name="ArtID" value="@item?.ArtID" hidden />
        <button type="submit" class="form-control" id="submit"> > </button>
    </div>
</for*@m>

ArtSocial/ArtSocial/Views/Product/Search.cshtml
@model IList<DetailProduct>
<header class="site-header d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12 text-center">

                <h2 class="mb-0">Danh sách tác phẩm</h2>
            </div>

        </div>
    </div>
</header>


<section class="latest-podcast-section section-padding pb-0" id="section_2">
    <div class="container">
        <div class="col-lg-12 col-12 mx-auto">
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-lg justify-content-center mt-5">
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>

                    <li class="page-item "><a class="page-link" href="/list-tac-pham1">Trừu tượng</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham2">Logo</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham3">Banner</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham4">Poster</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham5">Nữ tính</a></li>

                    <li class="page-item"><a class="page-link" href="/list-tac-pham6">3D</a></li>

                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        <div class="row justify-content-center">

            <div class="col-lg-12 col-12">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">Danh sác tác phẩm</h4>
                </div>
            </div>
            @if (Model.Count() == 0)
            {
                <h5 style="color:blueviolet"> ----------------      Hiện chưa có tác phẩm nào       -------------------</h5>
            }

            @foreach (var item in Model)
            {
                string url = "/tac-pham-" + item.ArtID.ToString();
                <div class="col-lg-6 col-12 mb-4">
                    <div class="custom-block d-flex">
                        <div class="">
                            <div class="custom-block-icon-wrap">
                                <div class="section-overlay"></div>
                                <a href="detail-page.html" class="custom-block-image-wrap">
                                    <img src="@item.Image" alt="" height="112px" width="112px">


                                </a>
                            </div>

                            <div class="mt-2">
                                <a href="#" class="btn custom-btn">
                                    Subscribe
                                </a>
                            </div>
                        </div>

                        <div class="custom-block-info">
                            <div class="custom-block-top d-flex mb-1">
                                <small class="me-4">
                                    <i class="bi-clock-fill custom-icon"></i>
                                    50 Minutes
                                </small>

                                <small>Episode <span class="badge">15</span></small>
                            </div>

                            <h5 class="mb-2">
                                <a href="@url">
                                    @item.ArtName
                                </a>
                            </h5>

                            <div class="profile-block d-flex">
                                <img src="~/@item.AvatarPath" class="profile-block-image img-fluid" alt="">

                                <p>
                                    @item.FullName
                                    <img src="~/Web/images/verified.png" class="verified-image img-fluid" alt="">
                                    <strong>Thành viên</strong>
                                </p>
                            </div>

                            @*<p class="mb-0">@(new HtmlString(item.Description.Remove(48))) ...</p>*@
                            <p class="mb-0">@item.Abstract</p>
                            <div class="custom-block-bottom d-flex justify-content-between mt-3">
                                <a href="#" class="bi-headphones me-1">
                                    <span>120k</span>
                                </a>

                                <a href="#" class="bi-heart me-1">
                                    <span>42.5k</span>
                                </a>

                                <a href="#" class="bi-chat me-1">
                                    <span>11k</span>
                                </a>

                                <a href="#" class="bi-download">
                                    <span>50k</span>
                                </a>
                            </div>
                        </div>

                        <div class="d-flex flex-column ms-auto">
                            <a href="#" class="badge ms-auto">
                                <i class="bi-heart"></i>
                            </a>

                            <a href="#" class="badge ms-auto">
                                <i class="bi-bookmark"></i>
                            </a>
                        </div>
                    </div>
                </div>

            }

        </div>

    </div>
</section>
@await Component.InvokeAsync("RecentArtView")