ArtSocial/ArtSocial/Areas/Admin/Controllers/LoginAdminController.cs
using ArtSocial.Models;
using ArtSocial.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace ArtSocial.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoginAdminController : Controller
    {
        private readonly DataContext _context;
        public LoginAdminController(DataContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(User user)
        {
            if (user == null)
            {
                return NotFound();
            }


            string pw = Functions.MD5Password(user.Password);
            var check = _context.Users.Where(m => (m.UserName == user.UserName) && (m.Password == pw) ).FirstOrDefault();
            if (check == null || check.isAdmin == false)
            {
                Functions._Message = "Tên đăng nhập hoặc mật khẩu khum đúng =)";
                return RedirectToAction("Index", "Loginadmin");
            }
            Functions._AdminID = check.UserID;
            Functions._AdminUser = String.IsNullOrEmpty(check.UserName) ? String.Empty : check.UserName;
            return RedirectToAction("Index", "Home");
        }
    }
}

ArtSocial/ArtSocial/Areas/Admin/Views/LoginAdmin/Index.cshtml
@model ArtSocial.Models.User;
@using ArtSocial.Utilities;
@{
	Layout = null;
}
<!doctype html>
<html lang="en">


<head>
	<title>Đăng nhập</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="preconnect" href="https://fonts.googleapis.com">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&family=Sono:wght@200;300;400;500;700&display=swap" rel="stylesheet">


	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="~/LoginWeb/css/style.css">

</head>
<body class="img js-fullheight" style="background-image: url(/LoginWeb/images/bg.jpg);">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">(admin)Đăng nhập</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
						<h3 class="mb-4 text-center">Đã có tài khoản?</h3>


						<form novalidate asp-controller="LoginAdmin"  asp-action="Index" asp-area ="admin" class="signin-form">
							<div class="form-group">
								<input type="text" class="form-control" placeholder="Tài khoản" asp-for="UserName" required>
							</div>
							<div class="form-group">
								<input id="password-field" type="password" class="form-control" placeholder="Mật khẩu" asp-for="Password" required>
								<span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
							</div>
							<div class="form-group">
								<button type="submit" class="form-control btn btn-primary submit px-3">Đăng nhập</button>
							</div>
							<div class="form-group d-md-flex">
								<div class="w-50">
									<label class="checkbox-wrap checkbox-primary">
										Nhớ
										<input type="checkbox" checked>
										<span class="checkmark"></span>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="/Register/Index" style="color: #fff">Đăngg ký</a>
								</div>
							</div>
						</form>
						<p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
						<div class="social d-flex text-center">
							<a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
							<a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<script src="~/LoginWeb/js/jquery.min.js"></script>
	<script src="~/LoginWeb/js/popper.js"></script>
	<script src="~/LoginWeb/js/bootstrap.min.js"></script>
	<script src="~/LoginWeb/js/main.js"></script>

</body>
</html>